#
# Final Consolidated MLOps Workflow
# Last updated: Thursday, October 9, 2025
# This workflow is fully aligned with the project's Makefile.
#
name: Model Training and Deployment CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write # Required for 'make update-branch' and 'gh release create'
  actions: read
  pull-requests: write

jobs:
  # --- JOB 1: Build, Test, and Package Artifacts ---
  # This job runs the core pipeline and tests, then packages the results.
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Cache pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Run the full training pipeline (install, train, eval)
      run: make pipeline
      
    - name: Run tests with pytest
      run: make test
        
    - name: Upload model artifacts
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: |
          Model/
          Results/
          report.md
        retention-days: 30

  # --- JOB 2: Deploy to Hugging Face and Create Release ---
  # This job only runs after 'build-and-test' succeeds on the main branch.
  deploy-and-release:
    needs: build-and-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download model artifacts from previous job
      uses: actions/download-artifact@v4
      with:
        name: model-artifacts
        
    - name: Commit model & results to 'update' branch
      run: make update-branch
        
    - name: Deploy all assets to Hugging Face Hub
      run: make deploy
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        
    - name: Create GitHub Release with Dynamic Notes
      run: |
        METRICS_CONTENT=$(cat Results/metrics.txt)

        RELEASE_NOTES="Automated model training and deployment.

        ## Model Performance
        \`\`\`
        ${METRICS_CONTENT}
        \`\`\`
        
        ## Changes
        - Model trained on latest data from commit ${{ github.sha }}
        - Deployed to Hugging Face Spaces
        - Model artifacts committed to the 'update' branch for tracking."

        gh release create model-v${{ github.run_number }} \
          --title "Model Release v${{ github.run_number }}" \
          --notes "$RELEASE_NOTES" \
          Model/drug_pipeline.joblib \
          Results/metrics.txt \
          Results/model_results.png
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}